stages:
  - build
  - test
  - deploy

before_script:
  - git submodule update --init --recursive

build_template_app:
  stage: build
  image: espressif/esp32-ci-env

  variables:
    SDK_PATH: "$CI_PROJECT_DIR"
    IDF_PATH: "$CI_PROJECT_DIR"
    GIT_STRATEGY: clone

  script:
    - git clone https://github.com/espressif/esp-idf-template.git
    - cd esp-idf-template
    # Try to use the same branch name for esp-idf-template that we're
    # using on esp-idf. If it doesn't exist then just stick to the default
    # branch
    - git checkout ${CI_BUILD_REF_NAME} || echo "Using esp-idf-template default branch..."
    - make defconfig
    - make all

test_nvs_on_host:
  stage: test
  image: espressif/esp32-ci-env
  script:
    - cd components/nvs_flash/test
    - make test

test_build_system:
  stage: test
  image: espressif/esp32-ci-env
  variables:
    IDF_PATH: "$CI_PROJECT_DIR"
  script:
    - ./make/test_build_system.sh

push_master_to_github:
  stage: deploy
  only:
    - master
  when: on_success
  image: espressif/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-idf.git
    - git push github HEAD:master
